services:
  main:
    ports:
      - ${N8N_PORT}:${N8N_PORT}

  db:
    ports:
      - 5432:5432

  qdrant:
    ports:
      - 6333:6333

  redis:
    ports:
      - 6379:6379

  adminer:
    ports:
      - 8080:8080

  redisinsight:
    ports:
      - 5540:5540
