services:
  server:
    image: itzg/minecraft-server
    restart: unless-stopped
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: 'TRUE'
      MEMORY: '4G'
      # For full modding platform (but seems like it doesn't work in ONLINE_MODE FALSE)
      # TYPE: 'FABRIC'
      OVERRIDE_SERVER_PROPERTIES: 'TRUE'
      ONLINE_MODE: 'FALSE'
    volumes:
      - ./data:/data
